name: JSON
on:
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Prettier
        run: docker run --rm -v ${PWD}:/work tmknom/prettier --list-different --parser=json '**/*.json'
