name: Shell Script
on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: ShellCheck
        uses: reviewdog/action-shellcheck@v1.1.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: build

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: shfmt
        run: docker run --rm -v ${PWD}:/work -w /work mvdan/shfmt:v3.1.0-alpine -i 2 -ci -kp -d .
